version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt-preview
            rustup update
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt
             git diff --exit-code
      - run:
          name: Test
          command: cargo test --target=x86_64-unknown-linux-gnu
      - run:
          name: Build
          command: cargo build --release
