version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup component add rustfmt
            rustup update
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt --all -- --check
      - run:
          name: Test
          command: |
             cargo test --target=x86_64-unknown-linux-gnu
             cargo test --release --target=x86_64-unknown-linux-gnu
      - run:
          name: Build
          command: |
             # debug
             cargo build
             # release
             cargo build --release
             # different allocators
             cargo build --release --features wee_alloc
             cargo build --release --features qimalloc
             # different allocators (no_std)
             cargo build --release --no-default-features --features wee_alloc
             cargo build --release --no-default-features --features qimalloc
             # different feature sets
             cargo build --release --no-default-features
             cargo build --release --features experimental
             cargo build --release --no-default-features --features experimental
             cargo build --release --features eth2
             cargo build --release --no-default-features --features eth2
             cargo build --release --features experimental,eth2
             cargo build --release --no-default-features --features experimental,eth2
