version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup target add wasm32-unknown-unknown
            rustup update
      - run:
          name: Build
          command: cargo build --release --target wasm32-unknown-unknown
