version: 2

jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Update rustc
          command: |
            rustup install nightly-x86_64-unknown-linux-gnu
            rustup target add wasm32-unknown-unknown --toolchain nightly
            rustup component add rustfmt
            rustup update
      - run:
           name: Check formatting
           command: |
             rustfmt --version
             cargo fmt --all -- --check
      - run:
          name: Test
          command: |
             cargo +nightly test --target=x86_64-unknown-linux-gnu
             cargo +nightly test --release --target=x86_64-unknown-linux-gnu
      - run:
          name: Build
          command: |
             # debug
             cargo +nightly build
             # release
             cargo +nightly build --release
             # different allocators
             cargo +nightly build --release --features wee_alloc
             cargo +nightly build --release --features qimalloc
             # different allocators (no_std)
             cargo +nightly build --release --no-default-features --features wee_alloc
             cargo +nightly build --release --no-default-features --features qimalloc
             # different feature sets
             cargo +nightly build --release --no-default-features
             cargo +nightly build --release --features debug
             cargo +nightly build --release --no-default-features --features debug
             cargo +nightly build --release --features experimental
             cargo +nightly build --release --no-default-features --features experimental
             cargo +nightly build --release --features experimental,debug
             cargo +nightly build --release --no-default-features --features experimental,debug
             cargo +nightly build --release --features eth2
             cargo +nightly build --release --no-default-features --features eth2
